import Head from 'next/head';

import styles from '@/styles/Home.module.scss';
import { CSSProperties, useEffect, useRef, useState } from 'react';
import axios from 'axios';

import Img from '@/components/utils/Img';
import Button from '@/components/button/Button';

export default function Home() {
    const [show, setShow] = useState(true);
    const [styleYes, setStyleYes] = useState<CSSProperties>({ fontSize: '1.2em' });
    const [styleNo, setStyleNo] = useState<CSSProperties>({});
    const [text, setText] = useState('Não');
    const [tries, setTries] = useState(0);
    const fontSize = useRef(1.5);
    const [currentImg, setCurrentImg] = useState('1.gif');

    useEffect(() => {
        if (localStorage.getItem('saw') === '1') return;
        axios
            .get('/api/hello')
            .then((res) => {
                console.log(res);
                localStorage.setItem('saw', '1');
            })
            .catch((err) => console.log(err));
    }, []);

    useEffect(() => {
        if (localStorage.getItem('choose') === '0') {
            setShow(false);
        }
    }, []);

    useEffect(() => {
        if (tries === 1) {
            setText('talvez tenha clicado errado kk');
        } else if (tries === 2) {
            setText('outra vez kk?');
            setCurrentImg('2.jpg');
        } else if (tries === 3) {
            setText('acho que você gosta de vermelho');
            setStyleYes((prevState) => ({ ...prevState, background: '#f00' }));
            setStyleNo((prevState) => ({ ...prevState, background: '#0f0' }));
            setCurrentImg('3.jpg');
        } else if (tries === 4) {
            setText('espera, tá clicando de propósito?');
            setStyleYes((prevState) => ({ ...prevState, background: '#0f0' }));
            setStyleNo((prevState) => ({ ...prevState, background: '#f00' }));
            setCurrentImg('4.jpg');
        } else if (tries === 5) {
            setText('clica sim aí, vai');
            setCurrentImg('6.jpg');
        } else if (tries === 6) {
            setText('é sério isso?');
            setCurrentImg('5.jpg');
        } else if (tries >= 7) {
            setText('já entendi...');

            setTimeout(() => setShow(false), 1500);
            localStorage.setItem('choose', '0');
            axios
                .post('/api/hello', { response: 'não' })
                .then((res) => {
                    console.log(res);
                })
                .catch((err) => console.log(err));
        }
    }, [tries]);

    function noOption() {
        const font = fontSize.current;
        setStyleYes({ fontSize: `calc(1.2em * ${font})` });
        fontSize.current += 0.5;
        setTries((prevState) => prevState + 1);
    }

    function yesOption() {
        axios
            .post('/api/hello', { response: 'sim' })
            .then((res) => {
                console.log(res);
            })
            .catch((err) => console.log(err));
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="./favicon.ico" />
            </Head>
            {show ? (
                <main className={`${styles.main}`}>
                    <div className={styles.main_image}>
                        <Img src={`/meme/${currentImg}`} />
                    </div>
                    <div className={styles.main_text}>
                        <p>Quer namorar comigo?</p>
                    </div>
                    <div className={styles.main_buttons}>
                        <div className={styles.main_button}>
                            <Button
                                text="Sim"
                                type="good"
                                style={styleYes}
                                handleFunction={yesOption}
                            />
                        </div>
                        <div className={styles.main_button}>
                            <Button
                                text={text}
                                type="bad"
                                style={styleNo}
                                handleFunction={noOption}
                            />
                        </div>
                    </div>
                </main>
            ) : (
                <div className={styles.main_err}>
                    <p>ok</p>
                </div>
            )}
        </>
    );
}
